# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('water_period', models.CharField(choices=[('DAILY', 'Once a day'), ('WEEKLY', 'Once a week'), ('BI-WEEKLY', 'Once every two weeks'), ('MONTHLY', 'Once a month')], max_length=255, verbose_name='Watering Period')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
